apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: read-k8s-events
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: registry.cn-hangzhou.aliyuncs.com/k8s-mirrors/k8s-events:latest