apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: test-image-to-docker-hub
  labels:
    expect: succeeded
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/yunlzheng/simple-app.git
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: docker.io/yunlzheng/app-from-source