apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: test-image-to-docker-hub
  labels:
    expect: succeeded
spec:
  serviceAccountName: build-bot-1
  source:
    git:
      url: https://github.com/yunlzheng/simple-app.git
      revision: master
  steps:
  - name: build-and-push
    image: registry.cn-hangzhou.aliyuncs.com/kaniko-project/executor
    args:
    - --dockerfile=/workspace/Dockerfile
    - --destination=docker.io/yunlzheng/app-from-source