apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass-1
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
  username: eXVubHpoZW5n
  password: emh5bDg3MjI1MDI4
